base: /Java-Levels/
description: All of the Java Levels
head:
- - meta
  - content: '#F37121'
    name: theme-color
- - meta
  - content: true
    name: apple-mobile-web-app-capable
- - meta
  - content: black
    name: apple-mobile-web-app-status-bar-style
plugins:
- '@vuepress/plugin-back-to-top'
- '@vuepress/plugin-medium-zoom'
themeConfig:
  displayAllHeaders: true
  docsDir: ''
  editLinkText: ''
  editLinks: false
  lastUpdated: false
  logo: /assets/Flag.png
  nav:
  - link: /about/
    text: About
  - link: https://jointheleague.org
    text: The LEAGUE
  repo: ''
  sidebar:
  - children:
    - path: /lessons/Module0/01_methods/
      title: Methods
    - path: /lessons/Module0/02_return_types/
      title: Return Types
    - path: /lessons/Module0/03_gui_with_help/
      title: Gui With Help
    - path: /lessons/Module0/04_gui_from_scratch/
      title: Gui From Scratch
    collapsable: false
    title: Module0
  - children:
    - path: /lessons/Module1/01_asteroids/
      title: Asteroids
    - path: /lessons/Module1/02_race_car/
      title: Race Car
    - path: /lessons/Module1/03_cat/
      title: Cat
    - path: /lessons/Module1/04_harry_potter/
      title: Harry Potter
    - path: /lessons/Module1/05_popcorn/
      title: Popcorn
    - path: /lessons/Module1/06_vault/
      title: Vault
    - path: /lessons/Module1/07_duck/
      title: Duck
    - path: /lessons/Module1/08_SolarSystem/
      title: Solarsystem
    - path: /lessons/Module1/09_HungryHungryHippos/
      title: Hungryhungryhippos
    - path: /lessons/Module1/10_turf_war/
      title: Turf War
    - path: /lessons/Module1/11_binary_converter/
      title: Binary Converter
    collapsable: false
    title: Module1
  - children:
    - path: /lessons/Module2/01_sea_creature/
      title: Sea Creature
    - path: /lessons/Module2/02_smurf/
      title: Smurf
    - path: /lessons/Module2/03_tea_maker/
      title: Tea Maker
    - path: /lessons/Module2/04_backpack/
      title: Backpack
    - path: /lessons/Module2/99_extra/
      title: Extra
    collapsable: false
    title: Module2
  - children:
    - path: /lessons/Module3/01_intro_to_static/
      title: Intro To Static
    - path: /lessons/Module3/02_static_smiley_blues/
      title: Static Smiley Blues
    - path: /lessons/Module3/04_netflix/
      title: Netflix
    - path: /lessons/Module3/05_cow_timer/
      title: Cow Timer
    - path: /lessons/Module3/06_frogger/
      title: Frogger
    - path: /lessons/Module3/99_extra/
      title: Extra
    collapsable: false
    title: Module3
  - children:
    - path: /lessons/Module4/01_chuckle_clicker/
      title: Chuckle Clicker
    - path: /lessons/Module4/02_jeopardy/
      title: Jeopardy
    - path: /lessons/Module4/03_typing_tutor/
      title: Typing Tutor
    - path: /lessons/Module4/04_book_of_illusions/
      title: Book Of Illusions
    - path: /lessons/Module4/05_fortune_teller/
      title: Fortune Teller
    - path: /lessons/Module4/06_calculator/
      title: Calculator
    - path: /lessons/Module4/07_tv_show_episode_info/
      title: Tv Show Episode Info
    - path: /lessons/Module4/08_pig_latin/
      title: Pig Latin
    - path: /lessons/Module4/09_whack_a_mole/
      title: Whack A Mole
    - path: /lessons/Module4/10_slot_machine/
      title: Slot Machine
    - path: /lessons/Module4/11_lights_out/
      title: Lights Out
    - path: /lessons/Module4/12_online_practice_quiz/
      title: Online Practice Quiz
    - path: /lessons/Module4/99_extra/
      title: Extra
    collapsable: false
    title: Module4
title: Java Levels
